parameters:
    upload_directory: '../__storage/'
    'app.owner': 'live-tools'
    'app.name': 'musicgame'
    'app.version': 'GPL-2'
services:
    _defaults:
        autowire: true      
        autoconfigure: true 
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\GithubService:
        arguments:
            $owner: 'live-tools'
            $repos: 'musicgame'
            $compressor: 'zip'

    App\Service\CsvFileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'